services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: feed_incident
      POSTGRES_PASSWORD: feed_incident
      POSTGRES_DB: feed_incident
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spark-master:
    image: apache/spark:4.0.0-java21-python3
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "7077:7077"
      - "8083:8080"
    volumes:
      - ./data:/opt/spark/data
      - ./logs/sparkmaster:/opt/spark/logs

  spark-worker-1:
    image: apache/spark:4.0.0-java21-python3
    container_name: spark-worker-1
    hostname: spark-worker-1
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/spark/data
      - ./logs/spark-worker-1:/opt/spark/logs

  spark-app:
    build: .
    container_name: spark-app
    hostname: spark-app
    depends_on:
      - spark-master
      - spark-worker-1
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    stdin_open: true
    tty: true
    volumes:
      - ./data:/opt/spark/data
      - ./logs/spark-app:/opt/spark/logs
    command: "/bin/bash"
    #"python3 /opt/spark/data/functionel_predict_incident_by_week.py"
      #>
      #python3 /opt/spark/data/functionel_predict_incident_by_week.py

volumes:
  pgdata:
